/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.7/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    application
    id("com.intershop.gradle.javacc") version "4.1.3"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)
}
javacc {
    configs {
        // Simple parser configuration
        create("simpleparser") {
            // Replace with your simple parser's .jj file
            inputFile = file("src/main/jj/MySimpleParser.jj")
            packageName = "org.example"  // Replace with your desired package name
        }
        create("parser") {
            inputFile = file("src/main/jj/parser.jj")
            packageName = "org.example"
            //lookahead = '2'
        }
    }

}
testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit4 test framework
            useJUnit("4.13.2")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}
