/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import javax.swing.JFrame;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
public class App {
    public static final int baseMulti = 1;
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        if (args.length > 0) {
            String inputFilePath = args[0];
            try {
                // Open the input file
                InputStream inputFileStream = new FileInputStream(inputFilePath);
                // Pass the file input stream to the parser
                MySimpleParser parser = new MySimpleParser(inputFileStream);
                GameConfig config = parser.parseGameConfig();

                System.out.println(new App().getGreeting());
                JFrame window = new JFrame(); 
                GamePanel gamePanel = new GamePanel(config);
                window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                window.setResizable(false);   
                window.setTitle("2d Maze");
                window.add(gamePanel);
                window.pack();
                window.setLocationRelativeTo(null);
                window.setVisible(true);
                gamePanel.setUpGame();
                gamePanel.startGameThread();

                // Uncomment the line below to call the parse method
                //parser.parseGameConfig();  // Call your parse method

                } catch (FileNotFoundException e) {
                System.out.println("File not found: " + inputFilePath);
                e.printStackTrace();
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            System.out.println("No input file provided.");
        }
        

        
    }
    public static int roundToNearestFive(int value) {
        return Math.round(value / 5.0f) * 5;
    }
}
